#!/usr/bin/env bash
# sync-product-context.sh
#
# Called by Claude Code's PostToolUse hook after Write/Edit tool calls.
# Regenerates docs/product-context-snapshot.md whenever a relevant source file changes.
#
# Relevant sources:
#   - docs/**/*.md
#   - prisma/schema.prisma
#   - CLAUDE.md
#   - src/lib/algorithms/*.ts (algorithm changes = business rule changes)
#   - src/lib/validations/*.ts (schema changes = data model changes)
#
# The snapshot is read by product-agent.md at the start of every invocation
# so it always has an up-to-date, pre-aggregated view of project state.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SNAPSHOT="$PROJECT_ROOT/docs/product-context-snapshot.md"

# Only regenerate if a relevant file was modified.
# $CLAUDE_TOOL_INPUT_FILE_PATH is set by the hook when available.
CHANGED_FILE="${CLAUDE_TOOL_INPUT_FILE_PATH:-}"

should_regenerate() {
  if [[ -z "$CHANGED_FILE" ]]; then
    return 0  # no info → regenerate to be safe
  fi

  case "$CHANGED_FILE" in
    */docs/*.md|\
    */prisma/schema.prisma|\
    */CLAUDE.md|\
    */src/lib/algorithms/*.ts|\
    */src/lib/validations/*.ts|\
    */docs/implementation-phases.md)
      return 0 ;;
    *)
      return 1 ;;
  esac
}

if ! should_regenerate; then
  exit 0
fi

TIMESTAMP="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

cat > "$SNAPSHOT" << SNAPSHOT_EOF
# FitTrack — Product Context Snapshot

> Auto-generated by \`.claude/scripts/sync-product-context.sh\`
> Last updated: ${TIMESTAMP}
> Do not edit manually — this file is overwritten on every relevant doc change.

---

## Implementation Status

$(grep -E '^\- \[.\]|^## Phase|^### Layer|^### Group|^\*\*Done when' "$PROJECT_ROOT/docs/implementation-phases.md" 2>/dev/null || echo "(could not read implementation-phases.md)")

---

## Active Business Rules

$(cat "$PROJECT_ROOT/docs/business-rules.md" 2>/dev/null || echo "(could not read business-rules.md)")

---

## Database Schema Summary

$(grep -E '^model |^\s+\w+ +\w+' "$PROJECT_ROOT/prisma/schema.prisma" 2>/dev/null | head -80 || echo "(could not read schema.prisma)")

---

## API Surface

$(grep -E '^\| (GET|POST|PUT|DELETE|PATCH)' "$PROJECT_ROOT/docs/api-routes.md" 2>/dev/null || echo "(could not read api-routes.md)")

---

## Feature Docs Index

$(for f in "$PROJECT_ROOT/docs/features/"*.md; do
  echo "### $(basename "$f")"
  head -20 "$f" 2>/dev/null
  echo ""
done)

SNAPSHOT_EOF

echo "[product-agent] Context snapshot updated: $SNAPSHOT"
